### ISSUE TITLE
SourceMapConcat: Concat: Vendor Styles/assets/vendor.css failed since upgrade to ember 2.13

### ISSUE THREAD

**Issue by RobIsHere** [ef4/fast-sourcemap-concat#34]
I don't include vendor.css at all, but don't know how to disable it. However this worked on earlier version of Ember:

```
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor Styles/assets/vendor.css] failed with:
Error: ENOENT: no such file or directory, open '/var/www/control/tmp/source_map_concat-input_base_path-Uk8j7tdv.tmp/vendor/addons.css'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at SourceMap.addFile (/var/www/control/node_modules/fast-sourcemap-concat/lib/source-map.js:75:31)
    at /var/www/control/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (native)
    at Concat.<anonymous> (/var/www/control/node_modules/broccoli-concat/concat.js:198:24)
    at /var/www/control/node_modules/fast-sourcemap-concat/lib/source-map.js:393:12
    at initializePromise (/var/www/control/node_modules/rsvp/dist/rsvp.js:589:5)
    at new Promise$1 (/var/www/control/node_modules/rsvp/dist/rsvp.js:1077:33)
    at SourceMap.end (/var/www/control/node_modules/fast-sourcemap-concat/lib/source-map.js:380:10)

The broccoli plugin was instantiated at:
    at Concat.Plugin (/var/www/control/node_modules/broccoli-plugin/index.js:7:31)
    at new Concat (/var/www/control/node_modules/broccoli-concat/concat.js:38:10)
    at module.exports (/var/www/control/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp._concatFiles (/var/www/control/node_modules/ember-cli/lib/broccoli/ember-app.js:432:12)
    at EmberApp.styles (/var/www/control/node_modules/ember-cli/lib/broccoli/ember-app.js:1341:32)
    at EmberApp.toArray (/var/www/control/node_modules/ember-cli/lib/broccoli/ember-app.js:1665:12)
    at EmberApp.toTree (/var/www/control/node_modules/ember-cli/lib/broccoli/ember-app.js:1686:38)
    at module.exports (/var/www/control/ember-cli-build.js:156:16)
    at Builder.setupBroccoliBuilder (/var/www/control/node_modules/ember-cli/lib/models/builder.js:56:19)
    at new Builder (/var/www/control/node_modules/ember-cli/lib/models/builder.js:30:10)
```

**Comment by stefanpenner** [comment]
I'm not sure this is an issue with this library, as it merely concats what we tell it to.

My recommendation is to put together a thorough reproduction, and if the problem still arises open an issue on ember-cli \w that reproduction.
