### ISSUE TITLE
Error: Cannot find module 'sourcemap-validator'

### ISSUE THREAD

**Issue by ming-codes** [ef4/fast-sourcemap-concat#37]
New release, new bugs.

**Comment by michaelfich** [comment]
Getting the same issue as well.

**Comment by ef4** [comment]
Thanks, please try 1.2.2

**Comment by jasonmit** [comment]
Verified, thanks for the quick response!

**Comment by ef4** [comment]
When you break something that's used by ember-cli you find out pretty fast. 😄

**Comment by danfike** [comment]
@ef4 Given https://github.com/ef4/fast-sourcemap-concat/blob/master/lib/source-map.js#L11 should we move `heimdalljs-logger` up as well?

I'm hitting problems with `heimdalljs-logger` missing in my `ember-cli` environment.
```
> cd ember-cli && node node_modules/ember-cli/bin/ember build --environment=production

WARNING: Node v6.11.1 has currently not been tested against Ember CLI and may result in unexpected behaviour.
version: 1.13.13
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Building
Cannot find module 'heimdalljs-logger'
Error: Cannot find module 'heimdalljs-logger'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (<snip>/ember-cli/node_modules/ember-cli-mocha/node_modules/broccoli-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:11:42)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
